-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 15:02:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_zurah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_zurah` DEFAULT CHARACTER SET utf8 ;
USE `db_zurah` ;

-- -----------------------------------------------------
-- Table `db_zurah`.`tb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_zurah`.`tb_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name_cat` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_zurah`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_zurah`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `is_seller` TINYINT NOT NULL,
  `photo` VARCHAR(1000) NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_zurah`.`tb_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_zurah`.`tb_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `expire` DATE NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `quantity` INT NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(500) NULL,
  `region` VARCHAR(255) NULL,
  `tb_category_id` BIGINT NOT NULL,
  `tb_users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_category_id`, `tb_users_id`),
  INDEX `fk_tb_product_tb_category_idx` (`tb_category_id` ASC) VISIBLE,
  INDEX `fk_tb_product_tb_users1_idx` (`tb_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_product_tb_category`
    FOREIGN KEY (`tb_category_id`)
    REFERENCES `db_zurah`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_product_tb_users1`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `db_zurah`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
